### PR TITLE
Include basic CLI script

### PR DESCRIPTION
**Pull request by Grokzen**
Currently the `run.py` script is basiccly useless in this repo. It serve more as a example script on how to run the bot more then something you can use. This solves this problem by creating a proper cli script when you install this package. This also removes the need for me to have a cli entrypoint inside my package and plugins repo to just run the bot.

How to use it after these changes.
- Create your own repo with a plugins folder and a `mattermost_bot_settings.py` file where you can code your bot plugins
- Create a new virtualenv
- Install `mattermost_bot` package in the venv
- Install your own code in the venv
- Run the bot with `MATTERMOST_BOT_SETTINGS_MODULE=mybots.settings.mattermost_bot_settings matterbot`
- My custom settings file will contains the `PLUGINGS` variable that will load all my custom bot code.

Questions that needs answering:
- What the CLI script should be called. I like `matterbot` but if you have any other suggestion, i can change it to whatever.

### CODE REVIEW

**Comment by Grokzen** [comment]
One other thing, can you please start to tag this repo on the commits that you are pushing to pypi?? There is no way to track what is included in the releases right now, except for guessing or inspecting the code.

**Comment by gotlium** [comment]
Current release is 1.0.9 https://github.com/LPgenerator/mattermost_bot/commit/bebcf254cbf03bc5964aaac218521cf999777c69
I think executable entry point good idea.

**Comment by gotlium** [comment]
Maybe you want create instructions for Ubuntu LTS with supervisor package from repo?

**Comment by Grokzen** [comment]
@gotlium There is no need to rollback the run.py file or introduce the ìf name =='main'` thing. Instead of having that script, here is how you should do to local develop.

I can agree to add back the try/except block inside my new main method to silence those exceptions in the new `cli.py`

- Create a new virtualenv
- CD to this package root
- Install this package as a local edtaible with `pip install -e .`
- Pip installs a symlink egg and installs all cli entrypoint scripts and all dependencies

With this setup and because it is a symlink inside the virtualenv, you can edit all the source code and run any cli scripts withouth having to reinstall the package all the time, or have the need for specialized scripts to run the code.

I can give it a try for the supervisord instructions, but i will do that in a new/seperate PR then because it might take some time before i have time to do it.

**Comment by gotlium** [comment]
1. Why rollback? You don't understand me. A talk about `make run`. I think you can add to Readme information about integration. e.g. django commands.
2. Ok about try/except block
3. I known about venv/pip and etc.
4. That is only idea) You can do it if you want.

**Comment by Grokzen** [comment]
Ah, yes then i miss understood you :] i thought you was talking about `run.py` and not the make command. I will add it back.

Have you thought about the cli entrypoint name `matterbot`? Is that good or you want some other name?

**Comment by gotlium** [comment]
I like:) Good name :+1:

**Comment by Grokzen** [comment]
How about this? and what about the `integration, e.g. django commands`?? did not get what you ment about that part.

**Comment by gotlium** [comment]
I mean integration with Django. I think I can do it by myself.

**Comment by gotlium** [comment]
Now import_module not working, because current directory not on Python path

    $ MATTERMOST_BOT_SETTINGS_MODULE="bot_settings" matterbot
    Traceback (most recent call last):
      File "/home/matterbot/mm-env/bin/matterbot", line 9, in <module>
        load_entry_point('mattermost-bot==1.0.10', 'console_scripts', 'matterbot')()
      File "/home/matterbot/mm-env/local/lib/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/home/matterbot/mm-env/local/lib/python2.7/site-packages/pkg_resources.py", line 2321, in load_entry_point
        return ep.load()
      File "/home/matterbot/mm-env/local/lib/python2.7/site-packages/pkg_resources.py", line 2048, in load
        entry = __import__(self.module_name, globals(),globals(), ['__name__'])
      File "/home/matterbot/mm-env/src/mattermost-bot/mattermost_bot/cli.py", line 5, in <module>
        from mattermost_bot import bot, settings
      File "/home/matterbot/mm-env/src/mattermost-bot/mattermost_bot/bot.py", line 15, in <module>
        from mattermost_bot import settings
      File "/home/matterbot/mm-env/src/mattermost-bot/mattermost_bot/settings.py", line 26, in <module>
        settings = importlib.import_module(settings_module)
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named bot_settings

but if I create run.py, all is working fine

    $ MATTERMOST_BOT_SETTINGS_MODULE="bot_settings" python run.py
    [02/15/2016 06:34:09] Starting new HTTP connection (1): localhost
    [02/15/2016 06:34:09] Starting new HTTP connection (1): localhost
    [02/15/2016 06:34:09] connected to mattermost
    [02/15/2016 06:34:09] loading plugin "mattermost_bot.plugins"
    [02/15/2016 06:34:09] registered respond_to plugin "ping_reply" to "ping"
    [02/15/2016 06:34:09] registered respond_to plugin "hello_reply" to "hello$"
    [02/15/2016 06:34:09] registered listen_to plugin "hello_reply_formatting" to "hello_formatting$"
    [02/15/2016 06:34:09] registered respond_to plugin "hello_reply_formatting" to "hello_formatting"
    [02/15/2016 06:34:09] registered listen_to plugin "hello_send" to "hello$"
    [02/15/2016 06:34:09] registered respond_to plugin "hello_decorators" to "hello_decorators"
    [02/15/2016 06:34:09] registered listen_to plugin "hello_decorators" to "hello_decorators"
    [02/15/2016 06:34:09] registered respond_to plugin "busy_reply" to "busy"
    [02/15/2016 06:34:09] keep active thread started

**Comment by gotlium** [comment]
You can install and check by following instruction https://github.com/LPgenerator/mattermost_bot/blob/master/docs/deploy.rst

**Comment by gotlium** [comment]
@Grokzen can you test by yourself deploy instructions?

**Comment by Grokzen** [comment]
@gotlium Hi. When can we expect a new tag with a `1.0.11` release? I would really like to get these things out to our bot in production with a proper pypi package/release? Are you expecting to add more functionality before a tag?

**Comment by gotlium** [comment]
`1.0.11` was released to PyPi. Try bot on production:)

**Pull request merged**
