### PR TITLE
allow posts to many teams

### PR DESCRIPTION
**Pull request by seLain**
Originally the bot can only posts to team specified in settings.py. This fix allowed the bot to respond in team channels wherever she was mentioned.

This fix should solve issue #39 and #45.

### CODE REVIEW

**Comment by attzonko** [comment]
I tested this and ran into an issue when adding the bot to new channels they were not previously a part of: Here is the traceback:
```
https://example.com:443 "GET /api/v3/teams/None/channels/3dbd1m4987fx7rubs81qygzjcr/ HTTP/1.1" 403 178
Traceback (most recent call last):
  File "/bot/bin/matterbot", line 11, in <module>
    sys.exit(main())
  File "/bot/local/lib/python2.7/site-packages/mattermost_bot/cli.py", line 18, in main
    b.run()
  File "/bot/local/lib/python2.7/site-packages/mattermost_bot/bot.py", line 37, in run
    self._dispatcher.loop()
  File "/bot/local/lib/python2.7/site-packages/mattermost_bot/dispatcher.py", line 116, in loop
    self._on_new_message(self.event)
  File "/bot/local/lib/python2.7/site-packages/mattermost_bot/dispatcher.py", line 92, in _on_new_message
    if self.is_mentioned(msg) or self.is_personal(msg):
  File "/bot/local/lib/python2.7/site-packages/mattermost_bot/dispatcher.py", line 54, in is_personal
    channel_type = channel['channel']['type']
KeyError: 'channel'
```

**Comment by attzonko** [comment]
To clarify once the bot is in the channel, it seems to work fine.

**Comment by seLain** [comment]
I made a workaround fix to reload teams/channels in user state when receiving these four websocket events: added_to_team, leave_team, user_added (to channel), user_removed (from channel). See if it works, thanks :)

**Comment by attzonko** [comment]
Tested your workaround and it works fine.

**Comment by attzonko** [comment]
I ran into another issue which I think results form these changes.

The mattermost.py in the get_profiles() we seem to use the default_team_id, however that ends up not getting all the correct profiles, especially if a message did not come from the default team id. so for example in dispatcher.py, where you try to get_user_info(), it tries to get_users() and ends up getting the wrong users. You can try to fix it by passing the current team id, but at this point that seems like a much bigger update.

Thoughts?

**Comment by attzonko** [comment]
I was indeed able to fix it, by passing the channel_id all the way down to get_profiles() Here is what that function was changed to to fix the issue.

    def get_profiles(self,channel_id=None, pagination_size=100):
        profiles = {}

        if channel_id is not None:
            team_id = self.get_team_id(channel_id)
        else:
            team_id = self.default_team_id

        start = 0
        end = start + pagination_size

        current_page = self.get('/teams/%s/users/0/%s'
                                % (team_id, pagination_size))
        profiles.update(current_page)
        while len(current_page.keys()) == pagination_size:
            start = end
            end += pagination_size
            current_page = self.get('/teams/%s/users/%s/%s'
                                    % (team_id, start, end))
            profiles.update(current_page)
        return profiles

**Comment by attzonko** [comment]
@seLain Any chance you can update this PR with the fix above to get_profiles()? I would like to request that this PR be merged but need that change.

**Pull request closed without merging**
